name: Deploy Laravel App to GoDaddy

on:
  push:
    branches:
      - deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1' # specify your PHP version
          extensions: mbstring, xml, curl, json, fileinfo, openssl, tokenizer

      - name: Install dependencies
        run: composer install --no-dev --prefer-dist --no-plugins --no-scripts -q -o

      - name: Ensure Server Directory Exists
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.GODADDY_FTP_SERVER }}
          username: ${{ secrets.GODADDY_FTP_USERNAME }}
          password: ${{ secrets.GODADDY_FTP_PASSWORD }}
          command: "mkdir -p /path/on/server/your_folder" # Replace with the actual path on the server
          continue-on-error: true # Ensures workflow continues even if folder exists

      - name: Upload files via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.GODADDY_FTP_SERVER }}
          username: ${{ secrets.GODADDY_FTP_USERNAME }}
          password: ${{ secrets.GODADDY_FTP_PASSWORD }}
          command: "mkdir -p /home/vmwki66izwq7/public_html/_libray_API/"
          server-dir: ./_libray_API/

      - name: Run migrations
        run: php artisan migrate --force
        env:
          APP_ENV: production
          APP_KEY: ${{ secrets.APP_KEY }} # set up APP_KEY as secret
          DB_CONNECTION: mysql
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
